name: STLs

# build for each push and pull request
on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout repo submodules
        run: git submodule update --init

      - name: Install dependencies
        run: sudo apt-get install -y openscad zip

      - name: Render STLs
        run: |
          ./3dprint/generate_stls.sh

      - name: Upload part files
        uses: actions/upload-artifact@v4.0.0
        with:
          name: drumkit-stl
          path: 3dprint/stl
          if-no-files-found: error

      - name: Archive release files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd 3dprint
          zip -r drumkit-stl stl

      - name: Upload release files
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: 3dprint/drumkit-stl.zip
